From oven/bun:1
WORKDIR /usr/src/app

COPY ./packages ./packages
COPY ./package.json ./package.json

COPY ./bun.lock ./bun.lock
COPY ./turbo.json ./turbo.json

copy ./apps/backend  ./apps/backend

run bun install
run bun run db:generate

expose 8080

CMD ["bun","run","start:backend"]





