FROM oven/bun:1

WORKDIR /usr/src/app

copy ./packages ./packages
copy ./packages.json ./package.json

copy ./bun.lock ./bun.lock
copy ./turbo.json ./turbo.json

run bun install
run bun run db:generate

expose 8081

CMD [ "bun","run","start:websocket"]

